# TODO: our open-next adapter outputs a worker.ts file, meaning that for deployments we rely on wrangler's bundling right?
#       this doesn't sound like the correct approach here, is it? is this intentional?
main = ".open-next/worker.js"
name = "nodejs-website"
compatibility_date = "2024-11-07"
compatibility_flags = ["nodejs_compat"]
account_id = "fb4a2d0f103c6ff38854ac69eb709272"

[observability]
enabled = true
head_sampling_rate = 1

[alias]
"node:fs" = "./.cloudflare/node/fs.mjs"
"node:fs/promises" = "./.cloudflare/node/fs/promises.mjs"
"server-only" = "./.cloudflare/server-only.mjs"
"@opentelemetry/api" = "./.cloudflare/opentelemetry.mjs"
# There is a `require("react-dom/server.edge")` in the `pages.runtime.prod.js` file
# but there isn't a `server.edge` entry in the `react-dom` package, so we just replace
# it with the existing `server.browser` (we should investigate why we have this behavior
# in the first place)
"react-dom/server.edge" = "react-dom/server.browser"
"jimp" = "./.cloudflare/empty.mjs"
"probe-image-size" = "./.cloudflare/empty.mjs"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
